### ISSUE TITLE
App crashes when we open Settings from the Navigation Drawer

### ISSUE THREAD

**Issue by neelanshsahai** [Eajy/MaterialDesignDemo#2]
I would like to work on this issue

**Comment by Eajy** [comment]
Hi.
I have noticed this crash. It will happens sometimes on Android 5.0 only.
And I still don't know the reason.

-- By Eajy

On May 16, 2017 23:49, "Neelansh Sahai" <notifications@github.com> wrote:

I would like to work on this issue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Eajy/MaterialDesignDemo/issues/2>, or mute the thread
