### ISSUE TITLE
Add a fragment which opens when a card is clicked

### ISSUE THREAD

**Issue by surbhitrao** [Eajy/MaterialDesignDemo#9]
Please add a additional fragment which opens when one of the cards is clicked

**Comment by Eajy** [comment]
Hey,
Which card you mean ? In the main page or?

-- By Eajy

**Comment by surbhitrao** [comment]
Yes in the main page.Set up its onClick so that the current fragment gets replaced with a new one.I am having some problem trying to replace fragment in the tab view.

![screenshot_20170726-101152](https://user-images.githubusercontent.com/13431596/28607803-1ff00e9a-71fb-11e7-8352-9651c569b0e4.jpg)

**Comment by Eajy** [comment]
Ok understood.
But it's not easy to replace a new fragment, because the tab fragments are
in the viewpager.

-- By Eajy


On Jul 26, 2017 14:38, "Surbhit Rao" <notifications@github.com> wrote:

Yes in the main page.Set up its onClick so that the current fragment gets
replaced with a new one.I am having some problem trying to replace fragment
in the tab view.

[image: screenshot_20170726-101152]
<https://user-images.githubusercontent.com/13431596/28607803-1ff00e9a-71fb-11e7-8352-9651c569b0e4.jpg>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Eajy/MaterialDesignDemo/issues/9#issuecomment-317962504>,
or mute the thread

**Comment by surbhitrao** [comment]
Please try to resolve it ASAP as it is an important functionality that your app should offer.

**Comment by rmarquis** [comment]
> Please try to resolve it ASAP as it is an important functionality that your app should offer.

@surbhitrao You should sincerely reconsider your tone. This is an excellent Demo app, and @Eajy was kind to make its source available to anyone. You can try to solve the issue by yourself and send a Pull Request, but please don't treat people as your personal slave.

**Comment by Eajy** [comment]
Hey,
I'm sorry that made you feel my bad tone. I'm a Chinese guy and my English
is very poor. Maybe my poor English let you feel that. I'm really sorry. And
I will never treat people as my personal salve.

And for the project I will try to solve this issue. But also I'm just a
junior Android developer and I'm busy usually. so it is really hard for me
to solve this. But I will try my best to do this.

-- By Eajy


On Jul 26, 2017 21:38, "Surbhit Rao" <notifications@github.com> wrote:

Closed #9 <https://github.com/Eajy/MaterialDesignDemo/issues/9>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Eajy/MaterialDesignDemo/issues/9#event-1179899930>, or mute
the thread

**Comment by rmarquis** [comment]
@Eajy My comment was directed at @surbhitrao, not you. Sorry for the misunderstanding. Your app is fantastic, and you deserve lot of respect for making it open source. I hope I'll be able to contribute to it! Well done! 做得好, 谢谢你!

**Comment by Eajy** [comment]
Oh haha. 🤣
Sorry for the misunderstanding.
And thank you Remy Marquis.
It's nice of you.
Hope you a good day😜

-- By Eajy


On Jul 26, 2017 23:34, "Remy Marquis" <notifications@github.com> wrote:

@Eajy <https://github.com/eajy> My comment was directed at @surbhitrao
<https://github.com/surbhitrao>, not you. Sorry for the misunderstanding.
Your app is fantastic, and you deserve lot of respect for making it open
source. I hope I'll be able to contribute to it! Well done! 做得好, 谢谢你!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Eajy/MaterialDesignDemo/issues/9#issuecomment-318091249>,
or mute the thread

**Comment by surbhitrao** [comment]
I am sorry if I sounded rude but all I meant to say that @Eajy 's wonderful Demo will be much more useful if that functionality could be added.I believe @rmarquis needs to learn some manners before pointing fingers at others.@Eajy  you have done a superb job and sorry once again.And @rmarquis  its @Eajy's repo and if he hasn't taken any offence then what is your problem mate?

**Comment by Eajy** [comment]
Hey guys,
@surbhitrao it's ok I understand. And thank you for your suggestions. And I believe @rmarquis not deliberately to pointing fingers at you. 
And I will try to add this function. But also you know that I'm just a junior developer and I'm really busy at office. so it is really hard for me to do this. I will try. Or you could add this by your self, it will be great.
Anyway I really thank you all for liking this app and support me. Let's be peaceful and understanding with each other.
